name: Python application CI/CD Aizaz Ahmed
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
       
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker login -u ${{secrets. DOCKER_USERNAME}} -p ${{secrets. DOCKER_PASSWORD}}
          docker build -t aizazahmed7/i200406-javamaven .
      - name: Push Docker Image
        run: docker push aizazahmed7/i200406-javamaven
